name: simple_dialog
version: 1.0.0
description: A library for simple dialogs.

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
